# Generated by Django 6.0.6 on 2026-06-14 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
