# Generated by Django 6.0.6 on 2026-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
    ]
